spring.application.name=btl_web
# Database connection
spring.datasource.url=""
spring.datasource.username=""
spring.datasource.password=""

# JPA settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect